### PR TITLE
Changelog for the release of PHPCompatibilityJoomla 2.1.3

### PR DESCRIPTION
**Pull request by jrfnl**
@mbabker Well, after lots of delays, we're finally close to PHPCompatibility 10.0.0... pfff
So.. this is just a small release to offload any changes made in the interim ahead of the next major.
I will tag the release after I've updated and released a similar release for the other PHPCompatibility* repos to make sure that when people update, they will get the latest version of the underlying packages as well.

Are there any changes in the polyfills Joomla provides which should be included still ?

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Comment by jrfnl** [comment]
> ... looking at the Composer manifests for the supported branches, there aren't any polyfills shipped for anything past PHP 7.3 so I don't think there are any changes needed here.

Thanks for letting me know. 👍🏻 

> I'm not following Joomla development anymore,
> @Hackwar as you seem to be looking at more static analysis things in Joomla, perhaps this tool might be of interest to you.

Genuine question - @mbabker would you still like to stay involved ? or does this mean you'd prefer to step down as a maintainer and pass the baton on to @Hackwar ? Or would you like for us to invite @Hackwar as a second Joomla-community based maintainer for this package ? (so many options)

@Hackwar I've had a quick look at the PR you linked and the "split off" PRs. Would you like some feedback ?

Also, please be aware that the `develop` branch of PHPCompatibility contains lots of additional checks, in particular around PHP 8.0 and 8.1. We're hoping to release version 10.0.0 soonish, but might be worth it to do a test run with bleeding edge PHPCompatibility.

**Comment by mbabker** [comment]
If someone else would like to step up, it'd be better for everyone involved.  As I said, I'm no longer involved with the core project.  Work-wise, we don't have many active Joomla clients with us anymore, so I'm just not actively working with the software these days.

**Comment by Hackwar** [comment]
@jrfnl Yes, I'd very much like feedback. :-) Thank you, @mbabker, for handling this in the past. I guess I should take this over from here? What would that entail? What do you need from me? I'm stirring a lot of pots right now, so I might not get to this in the next few days, but I will have a look at the develop branch.

**Comment by jrfnl** [comment]
> I guess I should take this over from here? What would that entail? What do you need from me?

@Hackwar Well, this is a low traffic repo as most of the heavy lifting goes on in the main PHPCompatibility repo.

What being the "Joomla representative" in this repo entails is basically:
* Keeping an eye on Joomla itself and if/when Joomla adds polyfills for new PHP functionality (including potentially adding polyfills via Composer dependencies), submitting a PR to add an exception for those to the `ruleset.xml` file. See https://github.com/PHPCompatibility/PHPCompatibilityJoomla/pull/7 for an example.
* Once in a while reviewing/approving/merging PRs from others (mostly me) in this repo. Some of those will be updates related to new releases of PHPCompatibility (example: https://github.com/PHPCompatibility/PHPCompatibilityJoomla/pull/8), most will just be CI/QA updates to keep everything running smoothly.

@mbabker Anything you'd like to add the above ?

> Yes, I'd very much like feedback. :-) 

I'll submit a PR review with some notes.

**Comment by mbabker** [comment]
> Anything you'd like to add the above ?

That's the gist of it.

Really the only times this ruleset needs an update from someone on the Joomla side of things is when platform requirements or packaged polyfills change (i.e. the current 4.2.4 package has the `symfony/polyfill-php80` package as a transient dependency, and the `symfony/polyfill-php72` package is still shipped even though it's unnecessary with the PHP 7.2 minimum), and it's not like those things are changing very often.

**Comment by jrfnl** [comment]
@Hackwar Just realizing this conversation was never really "finished". Would you like me to invite you to the repo ? If not, would you like to suggest someone else who could represent Joomla for this repo ?

**Pull request merged**
