### PR TITLE
Update for Joomla 3.9 release

### PR DESCRIPTION
**Pull request by mbabker**
Upcoming release included updated version of the Symfony PHP 7.3 polyfill, add new methods from that.

### CODE REVIEW

**Comment by jrfnl** [comment]
@mbabker As this is a functional change, I'm milestoning this for the `1.1.0` release and adjusting the milestones of previously merged PRs since the `1.0.0` release.

I imagine it would be most useful for this version to be released in sync with the Joomla 3.9.0 release (as in: around the same time) ?

**Comment by mbabker** [comment]
> You may still want to update the Joomla 3.9.0 composer.json file as the new functions are only included in the 1.9 version of the symfony/polyfill-php73 dependeny

One of these days someone really should check our minimum constraints in that file (maybe today's that day since it's a US holiday).

> I imagine it would be most useful for this version to be released in sync with the Joomla 3.9.0 release (as in: around the same time) ?

Agreed.

**Comment by jrfnl** [comment]
> > I imagine it would be most useful for this version to be released in sync with the Joomla 3.9.0 release (as in: around the same time) ?
>
> Agreed.

:+1: Will you ping me around that time or when you know the likely release date ?

IIRC all that should be needed is to update the changelog in the `readme.md` file, tagging the release, adding the changelog to the release and sending out a tweet announcing the release.

**Comment by mbabker** [comment]
It'll be mid-October, so still some time.  But yeah, I'll ping when we're there.

**Comment by jrfnl** [comment]
@mbabker In that case, we may already have another release before that time as I'm hoping to get PHPCompatibility 9.0.0 released before then and with the sniff recategorization, this ruleset will need to be updated for that as well.

**Pull request merged**
